name: Coupon Docker

on:
  push:
    branches: [ master ]
    
    paths:
      - coupon/**

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          image: diffen/50-lappen/coupon
          dockerfile: coupon/Dockerfile
          tags: latest
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
