name: Docker Image CI

on:
  push:
    branches: [ master ]


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build and push docker image
    
    - uses: mr-smithers-excellent/docker-build-push@v4
      name: Build & push Docker image
      with: 
        image: diffen/50-lappen
        tag: latest
        registry: docker.io
        username: -u ${{ secrets.DOCKER_USERNAME }} 
        password: -p ${{ secrets.DOCKER_PASSWORD }}
